name: workflow_load_hourly

on:
  schedule:
    - cron: '10 9-14 * * MON,TUE,WED,THU,FRI'

jobs:
  dbt_ci_jobs:
    name: dbt_workflow_hourly
    runs-on: ubuntu-latest
    environment: pro
    env:
      DBT_PROFILES_DIR: ./
      SYNAPSE_SERVER: ${{ secrets.SYNAPSE_SERVER }}
      DABATASE_SYNAPSE: ${{ secrets.DABATASE_SYNAPSE }}
      SCHEMA_SYNAPSE: ${{ secrets.SCHEMA_SYNAPSE }}
      AUTHENTICATION_SYNAPSE: ${{ secrets.AUTHENTICATION_SYNAPSE }}
      USER_SYNAPSE: ${{ secrets.USER_SYNAPSE }}
      PASSWORD_SYNAPSE: ${{ secrets.PASSWORD_SYNAPSE }} 
      SCHEMA_SILVER: ${{ secrets.SCHEMA_SILVER }} 
      SCHEMA_GOLD: ${{ secrets.SCHEMA_GOLD }}

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: "3.10.9"       
    
    - name: Install dependencies
      run: |
        pip install dbt-core==1.3.2
        pip install dbt-synapse==1.3.0
        dbt deps              

    - name: Run dbt debug
      run: dbt debug --target pro      

    - name: dbt build hourly
      run: dbt build --target pro --select tag:hourly --fail-fast